name: Deploy Project
on: push
jobs:
  latest_code:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@v4
  Code_test:
    needs: latest_code
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Project
        run: echo "Code Deployed" 
