name: Deploy Project
on: push
jobs:
  latest_code:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
<<<<<<< HEAD
      uses: actions/checkout@V6
=======
        uses: actions/checkout@V3
>>>>>>> 571036272a4f3be64e66136a82d349e39c1b86d3
  Code_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependency
        run: npm install 
      - name: Run Test
        run: |
          npm lint
          npm test
          npm build

