name: Deploy Project
on: push
jobs:
  latest_code:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout
  Code_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependency
        run: npm install 
      - name: Run Test
        run: |
          npm lint
          npm test
          npm build

